"""
Regras e dados das Atividades Complementares.

Os dados foram organizados com base no Apêndice I da Resolução nº 24/REIT-CONSUP/IFRO.
A linguagem foi simplificada para facilitar a consulta pelos estudantes.
"""

ATIVIDADES_COMPLEMENTARES = [
    {
        "item": 1,
        "atividade": "Participar como autor principal de projeto, diferente do TCC",
        "documento": "Certificado ou declaração",
        "por_atividade": "60h",
        "limite": "60h",
        "observacao": "Projeto em que o estudante é o autor principal ou bolsista.",
    },
    {
        "item": 2,
        "atividade": "Participar como colaborador de projeto, diferente do TCC",
        "documento": "Certificado ou declaração",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Projeto em que o estudante participa como colaborador.",
    },
    {
        "item": 3,
        "atividade": "Participar do PIBID",
        "documento": "Declaração",
        "por_atividade": "80h",
        "limite": "80h",
        "observacao": "Programa Institucional de Bolsas de Iniciação à Docência.",
    },
    {
        "item": 4,
        "atividade": "Participar do Programa de Residência Pedagógica",
        "documento": "Declaração",
        "por_atividade": "80h",
        "limite": "80h",
        "observacao": "Atividade vinculada à formação docente.",
    },
    {
        "item": 5,
        "atividade": "Participar de programa de internacionalização",
        "documento": "Certificado ou declaração",
        "por_atividade": "40h",
        "limite": "80h",
        "observacao": "Programa de internacionalização de pesquisa, ensino ou extensão.",
    },
    {
        "item": 6,
        "atividade": "Participar de mobilidade estudantil nacional ou internacional",
        "documento": "Certificado ou declaração",
        "por_atividade": "30h",
        "limite": "60h",
        "observacao": "Intercâmbio, mobilidade acadêmica ou experiência similar.",
    },
    {
        "item": 7,
        "atividade": "Participar de projeto que oferece produto ou serviço",
        "documento": "Declaração da instituição promotora",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Projeto prático ligado à oferta de produtos ou serviços.",
    },
    {
        "item": 8,
        "atividade": "Fazer disciplina extra relacionada ao curso",
        "documento": "Declaração ou histórico com ementa",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Disciplina fora da matriz obrigatória, mas ligada à formação.",
    },
    {
        "item": 9,
        "atividade": "Fazer monitoria",
        "documento": "Declaração",
        "por_atividade": "15h por semestre",
        "limite": "60h",
        "observacao": "Monitoria na área do curso ou em curso oferecido pelo IFRO.",
    },
    {
        "item": 10,
        "atividade": "Participar de grupo de estudo",
        "documento": "Certificado ou declaração",
        "por_atividade": "15h por semestre",
        "limite": "45h",
        "observacao": "Grupo de estudo comprovado por semestre.",
    },
    {
        "item": 11,
        "atividade": "Participar de grupo de pesquisa",
        "documento": "Certificado ou declaração",
        "por_atividade": "15h por semestre",
        "limite": "45h",
        "observacao": "Grupo de pesquisa comprovado por semestre.",
    },
    {
        "item": 12,
        "atividade": "Fazer curso complementar ou curso de línguas",
        "documento": "Certificado ou declaração",
        "por_atividade": "Até 10h: conta 5h | Até 30h: conta 15h | Acima de 30h: conta 20h",
        "limite": "60h",
        "observacao": "Cursos na área de formação ou cursos de línguas.",
    },
    {
        "item": 13,
        "atividade": "Assistir defesa de TCC ou trabalho de conclusão",
        "documento": "Declaração",
        "por_atividade": "2h",
        "limite": "20h",
        "observacao": "Participação como ouvinte.",
    },
    {
        "item": 14,
        "atividade": "Publicar livro completo com ISBN como autor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "30h",
        "limite": "60h",
        "observacao": "Livro completo publicado com ISBN.",
    },
    {
        "item": 15,
        "atividade": "Publicar capítulo de livro com ISBN como autor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "10h",
        "limite": "20h",
        "observacao": "Capítulo de livro publicado com ISBN.",
    },
    {
        "item": 16,
        "atividade": "Publicar artigo completo em periódico como autor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Artigo completo publicado ou aceito.",
    },
    {
        "item": 17,
        "atividade": "Publicar resumo expandido em evento como autor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "8h",
        "limite": "16h",
        "observacao": "Resumo expandido publicado ou aceito em anais.",
    },
    {
        "item": 18,
        "atividade": "Publicar resumo simples em evento como autor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "4h",
        "limite": "8h",
        "observacao": "Resumo simples publicado ou aceito em anais.",
    },
    {
        "item": 19,
        "atividade": "Publicar livro completo com ISBN como coautor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "15h",
        "limite": "30h",
        "observacao": "Coautoria de livro completo.",
    },
    {
        "item": 20,
        "atividade": "Publicar capítulo de livro com ISBN como coautor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "5h",
        "limite": "10h",
        "observacao": "Coautoria de capítulo de livro.",
    },
    {
        "item": 21,
        "atividade": "Publicar artigo completo em periódico como coautor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "10h",
        "limite": "20h",
        "observacao": "Coautoria de artigo completo.",
    },
    {
        "item": 22,
        "atividade": "Publicar resumo expandido em evento como coautor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "4h",
        "limite": "8h",
        "observacao": "Coautoria de resumo expandido.",
    },
    {
        "item": 23,
        "atividade": "Publicar resumo simples em evento como coautor",
        "documento": "Carta de aceite, declaração ou cópia da publicação",
        "por_atividade": "2h",
        "limite": "4h",
        "observacao": "Coautoria de resumo simples.",
    },
    {
        "item": 24,
        "atividade": "Apresentar trabalho em evento internacional",
        "documento": "Certificado ou declaração",
        "por_atividade": "5h",
        "limite": "20h",
        "observacao": "Comunicação oral, painel ou banner.",
    },
    {
        "item": 25,
        "atividade": "Apresentar trabalho em evento regional ou nacional",
        "documento": "Certificado ou declaração",
        "por_atividade": "4h",
        "limite": "16h",
        "observacao": "Comunicação oral, painel ou banner.",
    },
    {
        "item": 26,
        "atividade": "Apresentar palestra, minicurso ou oficina",
        "documento": "Certificado ou declaração",
        "por_atividade": "4h",
        "limite": "16h",
        "observacao": "Atividade apresentada pelo estudante.",
    },
    {
        "item": 27,
        "atividade": "Participar de comissão avaliadora de trabalhos",
        "documento": "Certificado ou declaração",
        "por_atividade": "2h",
        "limite": "10h",
        "observacao": "Avaliação de trabalhos em eventos.",
    },
    {
        "item": 28,
        "atividade": "Participar de evento internacional",
        "documento": "Declaração ou certificado",
        "por_atividade": "3h",
        "limite": "15h",
        "observacao": "Participação como ouvinte ou participante.",
    },
    {
        "item": 29,
        "atividade": "Participar de evento regional ou nacional",
        "documento": "Declaração ou certificado",
        "por_atividade": "2h",
        "limite": "10h",
        "observacao": "Participação como ouvinte ou participante.",
    },
    {
        "item": 30,
        "atividade": "Ajudar na organização de evento",
        "documento": "Declaração ou certificado",
        "por_atividade": "10h",
        "limite": "30h",
        "observacao": "Participação como membro da comissão organizadora.",
    },
    {
        "item": 31,
        "atividade": "Participar de colegiado do IFRO",
        "documento": "Declaração ou portaria",
        "por_atividade": "5h por semestre",
        "limite": "20h",
        "observacao": "Participação formal como membro de colegiado.",
    },
    {
        "item": 32,
        "atividade": "Representar o IFRO em evento externo",
        "documento": "Declaração ou portaria",
        "por_atividade": "5h",
        "limite": "20h",
        "observacao": "Representação formal do IFRO.",
    },
    {
        "item": 33,
        "atividade": "Produzir software ou hardware sem registro",
        "documento": "Produto apresentado em meio físico ou digital",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Exemplo: sistema, site, aplicativo, automação ou produto técnico.",
    },
    {
        "item": 34,
        "atividade": "Produzir software ou hardware com registro",
        "documento": "Produto apresentado em meio físico ou digital",
        "por_atividade": "40h",
        "limite": "80h",
        "observacao": "Produto com registro formal.",
    },
    {
        "item": 35,
        "atividade": "Produzir ou participar de evento artístico ou cultural",
        "documento": "Declaração ou certificado",
        "por_atividade": "10h",
        "limite": "20h",
        "observacao": "Atividade artística ou cultural comprovada.",
    },
    {
        "item": 36,
        "atividade": "Desenvolver material didático ou instrucional",
        "documento": "Carta de aceite, declaração ou cópia do material",
        "por_atividade": "10h",
        "limite": "30h",
        "observacao": "Material educativo, apostila, guia, manual ou semelhante.",
    },
    {
        "item": 37,
        "atividade": "Fazer estágio não obrigatório em outra instituição",
        "documento": "Certificado ou declaração",
        "por_atividade": "8h",
        "limite": "24h",
        "observacao": "Estágio que não faz parte da carga obrigatória do curso.",
    },
    {
        "item": 38,
        "atividade": "Fazer estudo ou atividade em instituição pública ou privada",
        "documento": "Declaração, certificado ou portaria",
        "por_atividade": "10h",
        "limite": "20h",
        "observacao": "Estudos ou atividades desenvolvidas fora do IFRO.",
    },
    {
        "item": 39,
        "atividade": "Produzir monografia não curricular",
        "documento": "Monografia com visto da coordenação",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Trabalho acadêmico extra, fora das disciplinas obrigatórias.",
    },
    {
        "item": 40,
        "atividade": "Fazer resenha de filme relacionado ao curso",
        "documento": "Resenha e declaração do professor orientador",
        "por_atividade": "2h",
        "limite": "10h",
        "observacao": "Filme deve ter relação com a área de formação.",
    },
    {
        "item": 41,
        "atividade": "Fazer leitura orientada de livro ou artigo",
        "documento": "Resenha e declaração do professor orientador",
        "por_atividade": "2h",
        "limite": "10h",
        "observacao": "Leitura extra, fora das disciplinas obrigatórias.",
    },
    {
        "item": 42,
        "atividade": "Apresentar atividade sociocultural ou artística",
        "documento": "Certificado ou declaração",
        "por_atividade": "5h",
        "limite": "10h",
        "observacao": "Exemplo: música, dança, teatro, vídeo, cinema ou fotografia.",
    },
    {
        "item": 43,
        "atividade": "Participar como ouvinte em atividade sociocultural ou artística",
        "documento": "Declaração da instituição ou organização promotora",
        "por_atividade": "2h",
        "limite": "10h",
        "observacao": "Participação como público/ouvinte.",
    },
    {
        "item": 44,
        "atividade": "Participar como atleta em jogos do IFRO",
        "documento": "Declaração",
        "por_atividade": "5h",
        "limite": "20h",
        "observacao": "Jogos promovidos pelo IFRO ou com participação formal do campus.",
    },
    {
        "item": 45,
        "atividade": "Receber premiação científica, técnica, artística ou semelhante",
        "documento": "Comprovante da premiação",
        "por_atividade": "20h",
        "limite": "40h",
        "observacao": "Prêmio ou condecoração por serviço ou produção relevante.",
    },
    {
        "item": 46,
        "atividade": "Atuar como voluntário em ação social ou acadêmica",
        "documento": "Declaração, certificado ou portaria",
        "por_atividade": "Até 10h: conta 5h | Até 30h: conta 8h | Acima de 30h: conta 10h",
        "limite": "40h",
        "observacao": "Voluntariado comprovado.",
    },
    {
        "item": 47,
        "atividade": "Doar sangue",
        "documento": "Declaração de doação",
        "por_atividade": "5h",
        "limite": "30h",
        "observacao": "Cada doação pode contar 5h, respeitando o limite.",
    },
    {
        "item": 48,
        "atividade": "Participar de campanha de prevenção à saúde",
        "documento": "Declaração ou certificado",
        "por_atividade": "1h",
        "limite": "30h",
        "observacao": "Campanhas de saúde, pandemia ou epidemias.",
    },
    {
        "item": 49,
        "atividade": "Prestar serviço eleitoral ao TRE",
        "documento": "Declaração",
        "por_atividade": "8h",
        "limite": "24h",
        "observacao": "Atuação comprovada em serviço eleitoral.",
    },
    {
        "item": 50,
        "atividade": "Outras atividades não listadas",
        "documento": "Documento que comprove a atividade",
        "por_atividade": "Depende da análise",
        "limite": "Depende da aprovação",
        "observacao": "Precisa ser analisada e aprovada pelo colegiado do curso.",
    },
]